### ISSUE TITLE
Console Errors

### ISSUE THREAD

**Issue by Gamekaiwa** [farling42/fvtt-export-markdown#3]
When launching Foundry v10 (build 303) on the Forge, and running 5e 2.3.1 I get the following errors:

```
Uncaught (in promise) LibWrapperPackageError: Error detected in module Markdown Exporter.

This is *not* a libWrapper bug.

Find information about this module here: https://github.com/farling42/fvtt-export-markdown

Ask the community for support:
- FoundryVTT Discord's #modules-troubleshooting channel: https://discord.gg/foundryvtt
- FoundryVTT Reddit: https://www.reddit.com/r/FoundryVTT

== Technical Details:
Detected by libWrapper.
Package ID= export-markdown
Error= Could not find target 'DocumentDirectory.prototype._getEntryContextOptions': Could not find root scope 'DocumentDirectory'.

    at pe (libWrapper-api.js:135:10)
    at de (libWrapper-api.js:152:19)
    at 🎁register [as register] (libWrapper-api.js:525:14)
    at Object.fn (export-markdown.js:565:16)
    at #call (foundry.js:724:20)
    at Hooks.callAll (foundry.js:681:17)
    at Game.initialize (foundry.js:7810:11)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at 🎁libWrapperInit (libWrapper-api.js:805:11)
```

This leads to multiple errors that "Document Directory is not defined."

(Sorry if this is the wrong place to post this, I am new to GitHub)

**Comment by farling42** [comment]
There were some aspects of the code which didn't work on Foundry V10, these have been fixed in version 0.9.1
